name:  Release New runner Image

on:
  pull_request:
    types: [ closed ]

jobs:
  docker_build_and_push:
    name: Build and Push API Docker Image for develop
    if: github.event.pull_request.merged == true && (github.base_ref == 'develop') && github.repository != 'LightricksResearch/comfyui_worker_serving'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          token: ${{ secrets.BOT_TOKEN }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/474377433429/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider'
          service_account: 'github-actions@ltx-research.iam.gserviceaccount.com'
    
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Push API Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          tags: |
           gcr.io/ltx-research/runner-arc:v0.0.1
          file: ./images/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
